### ISSUE TITLE
Multi-carousel: enhancements

### ISSUE THREAD

**Issue by Fred-OI** [open-interactive/helium#144]
- [x] dynamische Höhe
- [x] unterschiedlichen Slides-Breiten
- [x] continuous swiping

**Comment by pierresandrin-oi** [comment]
Review Fred

**Comment by zischler** [comment]
@Fred-OI wir sollte mal über die is-cover Logik schauen. Ich habe sie angepasst, da sie vorher keinen Sinn gemacht hat und beim Carousel immer isCover = true war.

**Comment by zischler** [comment]
Bugs die noch behoben werden müssen:
- [ ] Height calculation wenn keine ratio ausgewählt ist muss richtig funktionieren. Muss das höchste Bild nehmen dass nicht is-cover und das als default height nehmen bei voller breite von Bild.
- [ ] Infinite Slide mit zwei Bildern. js-last muss gleiches bild wie js-next sein. Also bei next klick wird js-next=js-last und umgekehrt js-last=js-next.
- [ ] Linear und absolute Carousel in Slider und Slideshow umbenennen. Slider ist wenn sich alle slides zusammen bewegen. Slideshow, wenn sich jede Slide selbst bewegt.

**Comment by zischler** [comment]
- [ ] Slider Funktionalität wieder zurückbringen. (Momentan alles Slideshow)
