### ISSUE TITLE
Rotstift Error Handling übernehmen

### ISSUE THREAD

**Issue by Dalibor22x** [open-interactive/helium#173]
Wäre gut wenn wir das gleich in Helium integrieren würden, oder?

**Comment by zischler** [comment]
Momentan wahrscheinlich nicht nötig in vielen Projekten. Wird hinzugefügt wenn sich das ändert.

**Comment by pierresandrin-oi** [comment]
Welches Error Handling? Custom Form? Können wir sonst im Helium Meeting besprechen.
