### ISSUE TITLE
Carousel.vue beinhaltet Code von Swipe.ts

### ISSUE THREAD

**Issue by zischler** [open-interactive/helium#203]
Warum sind die Touch Event Funktionen dupliziert? Man könnte einfach swipe importen, aufrufen und dann die Events handeln, die die Swipe Funktionen emitten.

Funktionen die dupliziert sind:
blockClick, touchStart, touchMove, touchEnd, OnWheel, getTouchEvent (branch carousel-10-19)

**Comment by zischler** [comment]
machen

**Comment by Dalibor22x** [comment]
@zischler Kann man das Ticket schliessen?

**Comment by zischler** [comment]
ja
