### ISSUE TITLE
Dialog Übersetzungen

### ISSUE THREAD

**Issue by Fred-OI** [open-interactive/helium#204]

**Comment by pierresandrin-oi** [comment]
Deutsch, Englisch

**Comment by pierresandrin-oi** [comment]
@Fred-OI Ich habe die Dialoge von allen wichtigen Komponenten Übersetzt. Teilweise habe ich die Texte ein wenig angepasst. Schau doch kurz ob alles ok ist.

**Comment by Fred-OI** [comment]
ok
