### ISSUE TITLE
Carousel: Slider ohne Width und Height ist zu klein

### ISSUE THREAD

**Issue by Dalibor22x** [open-interactive/helium#215]
Folgende Einstellungen:

![Bildschirmfoto 2019-11-07 um 10 02 21](https://user-images.githubusercontent.com/13834207/68374729-b3416500-0145-11ea-8d4d-c9cff69b6e46.png)

führen zu folgendem Fehler:

![Bildschirmfoto 2019-11-07 um 10 04 19](https://user-images.githubusercontent.com/13834207/68374860-fac7f100-0145-11ea-9d74-af591554993e.png)

**Comment by zischler** [comment]
Ein Slider ohne width und height, oder fixed ratio sollte nicht möglich sein. Zumindest ist das die alte höhenberechnung. Wenn ich die neue Einbinde müsste ich noch schauen wie sich das mit dem Slider machen lässt.

**Comment by zischler** [comment]
4/3 fallback bei slider

**Comment by pierresandrin-oi** [comment]
4/3 Fallback funktioniert.
