### ISSUE TITLE
Carousel: Height calculation bei Vertical Orientation falsch

### ISSUE THREAD

**Issue by zischler** [open-interactive/helium#231]
Wenn mehrere Items in einem Vertical Carousel sind, ist die Rechnung der Höhe falsch.
Es sollte die Slide Ratio für die Slides übernehmen. Vielleicht sollte das Carousel dann die Fixed Ratio als Ratio erhalten. (Muss man noch besprechen)
![Screenshot 2019-11-08 at 13 41 44](https://user-images.githubusercontent.com/26481494/68477345-87011380-022d-11ea-8393-dab4abe60aaa.png)

**Comment by zischler** [comment]
Dialog so lassen, descriptions hinzufügen. Damit man weiss was itemsperslide usw. ist.
Min width. Welche Breite die slides mind. haben müssen. Sonst werden zwei slides z.B. zu einem.
Bei max width das gleiche umgekehrt.

**Comment by pierresandrin-oi** [comment]
Ok
