### ISSUE TITLE
Lazy media renders svg

### ISSUE THREAD

**Issue by Fred-OI** [open-interactive/helium#72]

**Comment by cedeber** [comment]
https://github.com/open-interactive/ffbk/blob/d6cfb300d6aded35f05263e7f1a8acff0d15e998/magnolia/light-modules/main/templates/components/footer.ftl#L39

https://github.com/open-interactive/ffbk/blob/d6cfb300d6aded35f05263e7f1a8acff0d15e998/frontend/src/components/lazy-media.ts#L68

**Comment by cedeber** [comment]
#77
